# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TAL.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 568)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Arabic, QtCore.QLocale.Egypt))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("font: 75 13pt \"Bitstream Charter\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setStyleSheet("font: 75 16pt \"Bitstream Charter\";")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 5, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_4.addWidget(self.textEdit_2, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet("font: 75 11pt \"Bitstream Charter\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAutoFillBackground(True)
        self.label.setStyleSheet("font: 75 11pt \"Bitstream Charter\";\n"
"font: 75 11pt \"Bitstream Charter\";")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setTabChangesFocus(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 4, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.corpushow = QtWidgets.QPushButton(self.tab_4)
        self.corpushow.setObjectName("corpushow")
        self.gridLayout_5.addWidget(self.corpushow, 0, 1, 1, 1)
        self.quittershow = QtWidgets.QPushButton(self.tab_4)
        self.quittershow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.quittershow.setAutoFillBackground(True)
        self.quittershow.setCheckable(True)
        self.quittershow.setChecked(False)
        self.quittershow.setObjectName("quittershow")
        self.gridLayout_5.addWidget(self.quittershow, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.tab_4)
        self.treeView.setObjectName("treeView")
        self.gridLayout_6.addWidget(self.treeView, 1, 0, 1, 1)
        self.listView = QtWidgets.QListView(self.tab_4)
        self.listView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.listView.setAutoFillBackground(True)
        self.listView.setStyleSheet("\n"
"font: 75 11pt \"Bitstream Charter\";\n"
"")
        self.listView.setObjectName("listView")
        self.gridLayout_6.addWidget(self.listView, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkword = QtWidgets.QCheckBox(self.tab_5)
        self.checkword.setObjectName("checkword")
        self.horizontalLayout_7.addWidget(self.checkword)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.wordtext = QtWidgets.QTextEdit(self.tab_5)
        self.wordtext.setOverwriteMode(False)
        self.wordtext.setObjectName("wordtext")
        self.gridLayout_2.addWidget(self.wordtext, 1, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.period = QtWidgets.QComboBox(self.tab_5)
        self.period.setMinimumSize(QtCore.QSize(150, 0))
        self.period.setObjectName("period")
        self.verticalLayout_6.addWidget(self.period)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.genre = QtWidgets.QComboBox(self.tab_5)
        self.genre.setObjectName("genre")
        self.verticalLayout_7.addWidget(self.genre)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.toolBox = QtWidgets.QToolBox(self.tab_5)
        self.toolBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 679, 154))
        self.page.setMouseTracking(False)
        self.page.setObjectName("page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.editmeaning = QtWidgets.QLineEdit(self.page)
        self.editmeaning.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.editmeaning.setText("")
        self.editmeaning.setObjectName("editmeaning")
        self.horizontalLayout_8.addWidget(self.editmeaning)
        self.insertmeaning = QtWidgets.QPushButton(self.page)
        self.insertmeaning.setObjectName("insertmeaning")
        self.horizontalLayout_8.addWidget(self.insertmeaning)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.listmeaning = QtWidgets.QTableWidget(self.page)
        self.listmeaning.setObjectName("listmeaning")
        self.listmeaning.setColumnCount(0)
        self.listmeaning.setRowCount(0)
        self.listmeaning.horizontalHeader().setStretchLastSection(True)
        self.listmeaning.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.listmeaning)
        self.toolBox.addItem(self.page, "")
        self.Examples = QtWidgets.QWidget()
        self.Examples.setGeometry(QtCore.QRect(0, 0, 679, 162))
        self.Examples.setObjectName("Examples")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Examples)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.modifyexample = QtWidgets.QLineEdit(self.Examples)
        self.modifyexample.setObjectName("modifyexample")
        self.horizontalLayout_9.addWidget(self.modifyexample)
        self.insertexample = QtWidgets.QPushButton(self.Examples)
        self.insertexample.setObjectName("insertexample")
        self.horizontalLayout_9.addWidget(self.insertexample)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.label_4 = QtWidgets.QLabel(self.Examples)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.exampleslist = QtWidgets.QTableWidget(self.Examples)
        self.exampleslist.setObjectName("exampleslist")
        self.exampleslist.setColumnCount(0)
        self.exampleslist.setRowCount(0)
        self.exampleslist.horizontalHeader().setStretchLastSection(True)
        self.exampleslist.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_11.addWidget(self.exampleslist)
        self.toolBox.addItem(self.Examples, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_19.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_19.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 20))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menu.setFont(font)
        self.menu.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionquit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.actionquit.setFont(font)
        self.actionquit.setObjectName("actionquit")
        self.menu.addAction(self.actionquit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "تسجيل الدخول الاشتراك"))
        self.pushButton.setText(_translate("MainWindow", "تسجيل الدخول"))
        self.label_2.setText(_translate("MainWindow", "كلمة السر"))
        self.label.setText(_translate("MainWindow", "مؤلف المعجم"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "صحة المستندات"))
        self.corpushow.setText(_translate("MainWindow", "عرض كوربوس العربية"))
        self.quittershow.setText(_translate("MainWindow", "ترك"))
        self.label_8.setText(_translate("MainWindow", "هيكل من محتويات كوربوس العربية"))
        self.label_9.setText(_translate("MainWindow", "المحتوى المحدد"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "تصور"))
        self.checkword.setText(_translate("MainWindow", "تأكيد"))
        self.label_3.setText(_translate("MainWindow", "كلمة"))
        self.label_6.setText(_translate("MainWindow", "العصر:"))
        self.label_7.setText(_translate("MainWindow", "صنف:"))
        self.insertmeaning.setText(_translate("MainWindow", "Insert"))
        self.label_5.setText(_translate("MainWindow", "معنى"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "كلمة"))
        self.insertexample.setText(_translate("MainWindow", "Insert example"))
        self.label_4.setText(_translate("MainWindow", "أمثلة مرتبة حسب المقياس"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Examples), _translate("MainWindow", "أمثلة"))
        self.pushButton_5.setText(_translate("MainWindow", "إلغاء"))
        self.pushButton_4.setText(_translate("MainWindow", "تأكيد"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "مؤلف المعجم   "))
        self.menu.setTitle(_translate("MainWindow", "قائمة التطبيق"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionquit.setText(_translate("MainWindow", "&quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

